version: '2'
services:
  backend:
    build: './backend'
    volumes:
      - './backend:/app'
    ports:
      - '3030:3030'
    depends_on:
      - mongo
  frontend:
    build: './frontend'
    volumes:
      - './frontend:/app'
    ports:
      - '8080:8080'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
  nginx:
    image: nginx
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
